### ISSUE TITLE
Dark themes should have a dark toolbar (Linux)

### ISSUE THREAD

**Issue by KeitIG** [Jacse/themes-for-brackets#116]
Hi, 

With some Linux desktop environments, Themes use a custom toolbar and not the system one, the problem is whatever the theme is, it stays white.

Brackets default dark theme:
![capture du 2014-11-06 10 24 19](https://cloud.githubusercontent.com/assets/1311607/4933443/2e83fdc2-6597-11e4-9500-6acdc79e9c9c.png)

example with "Theme for Brackets - MBO"
![capture du 2014-11-06 10 24 34](https://cloud.githubusercontent.com/assets/1311607/4933446/3291ea64-6597-11e4-9c37-7ed3b9930b73.png)

This kinda hurts eyes,

best !

**Comment by wormeyman** [comment]
https://github.com/cristatus/brackets-darker/blob/master/main.js

Could we use this as an example? Unfortunately my java script knowledge is pretty limited, @Jacse could you fix this using the other theme pack as an example?

**Comment by Jacse** [comment]
@wormeyman I'll look into this in the weekend.

**Comment by Jacse** [comment]
Not quite sure how I'll debug this, considering I don't have a Linux machine, though

**Comment by Jacse** [comment]
@wormeyman @KeitIG I think we should leverage off this css - it styles the titlebar: https://github.com/cristatus/brackets-darker/blob/master/darker.css

**Comment by wormeyman** [comment]
I ended up using a virtual machine to test Linux.
