### ISSUE TITLE
New theme request

### ISSUE THREAD

**Issue by rioc0719** [Jacse/themes-for-brackets#122]
I actually made these themes for my personal use (and to quench my OCD). I did not know about the Bear Theme, so they aren't based on it, but I have incorporated parts of that theme into my themes. Most components of Brackets have been targeted. [Here's a screenshot of the dark theme] (http://i.imgur.com/pdUdiV3.jpg?1). To make this theme work correctly, the class on `<body>` must be changed to `dark` or certain elements won't be themed. The light theme is underway, so the only barrier to adding this theme is to change the `<body>` class (which should probably also be done for some of the other themes).

**Comment by wormeyman** [comment]
Hey @rioc0719 we are currently not accepting any new themes but I'll let Jacse feel free to weigh in if he wants. The best thing is to probably package it up as it's own independent theme. That way you can just use the package.json to set it as dark.

**Comment by Jacse** [comment]
While your theme does look really cool, @wormeyman is right. It is probably best for you to publish your theme independently. You are also able to update your theme yourself in that way.
