### ISSUE TITLE
Extension interferes with Brackets-File-Icons

### ISSUE THREAD

**Issue by mfromin** [Jacse/themes-for-brackets#125]
https://github.com/drewbkoch/Brackets-File-Icons
If I use this extension along with your themes extension the icons for the Brackets-File-Icons stop rendering and become simple rectangles with an X in the middle:  

![screen shot 2015-04-28 at 2 39 12 pm](https://cloud.githubusercontent.com/assets/2193139/7379769/5f4a9dc6-edb4-11e4-9d22-7db37680f04c.png)

As soon as I disable your extension this stops happening.  Any idea why?  I really like both extensions but can't use them together at present.

**Comment by mfromin** [comment]
FWIW the maker of that other extension tells me he runs 2.0.10 of this extension w/o issue.  I am on 2.0.11 and do have this issue.

**Comment by wormeyman** [comment]
Hi @mfromin I'm not running into the same error, could you let me know the following:

1. What Theme you are using?
1. What Operating System?
1. What Brackets Version?

For example I am running:
- Themes for brackets rubyblue
- Ubuntu 15.04
- Brackets 1.3

**Comment by mfromin** [comment]
**Theme:**  Themes for Brackets Obsidian
**OS:** Mac OS X 10.10.3
**Brackets:**  1.3

If I simply uninstall Themes for Brackets and leave all other extensions in place this issue no longer happens.

**Comment by wormeyman** [comment]
Do you receive any errors in the console? `Debug - Show developer tools` I ufortunately do not have a mac so I cannot test this :cry:

**Comment by mfromin** [comment]
I see one error related to the Bower extension (file permissions for a log) but nothing else.  I would note this also seems to mess with the icon that Brackets Git wants to put at the top of the Working Files list...

![screen shot 2015-04-29 at 9 54 50 pm](https://cloud.githubusercontent.com/assets/2193139/7406101/6b9bcf08-eeba-11e4-8696-1ee091af06a4.png)

Notice the left icon (next to the cog wheel) is a smaller version of the same "rectangle X" icon.

Is there a way to get the prior release of your extension (2.0.10) to see if that eliminates the issue?

**Comment by wormeyman** [comment]
https://github.com/Jacse/themes-for-brackets/releases

I tagged some releases so you can download and install the zip.

**Comment by wormeyman** [comment]
Also see if this version of the file icons works https://github.com/AdriVanHoudt/Brackets-File-Icons/archive/1.3.zip

It is one of the pull requests that fixes a small error for the icons extension.

**Comment by mfromin** [comment]
I know what is causing this now…

I wanted to change the font/size of the file names on the left side of Brackets.  I added this CSS to stuff.css:

.working-set-header-title,
.title,
#sidebar * {
    font-size: 14px;
    font-family: 'SourceCodePro-Medium', 'MS Gothic', monospace;
}

…and boom - things go bad for the icons.  Any idea how I can change the font & size using CSS that won’t cause this to blow up?

BTW - I really appreciate your help with this issue.  Bracket’s customizability is one of its best features but I appear to be good at breaking things!

--Michael

**Comment by wormeyman** [comment]
Just ditch the `font-family`

```css
.working-set-header-title,
.title,
#sidebar * {
    font-size: 14px;
}
```

**Comment by mfromin** [comment]
I actually wanted to change both the font and size...I don't care for the default font (getting old sucks).  After some playing this worked:

.working-set-header-title {
    font-size: 14px;
    font-family: 'SourceCodePro-Medium', 'MS Gothic', monospace;
}

.title * {
    font-size: 12px;
    font-family: 'SourceCodePro-Medium', 'MS Gothic', monospace;
}

#sidebar {
    font-size: 14px;
    font-family: 'SourceCodePro-Medium', 'MS Gothic', monospace;
}

Note the sidebar no longer has the asterisk (*) in the CSS.  This seems to solve the issue!
