### ISSUE TITLE
Some themes hide the git branch selection

### ISSUE THREAD

**Issue by mfromin** [Jacse/themes-for-brackets#126]
In some themes you have CSS like this:

#project-files-header {
    padding: 0;
}
#project-files-header .btn-alt-quiet {
    /* Folder button */
    border-radius: 0;
    width: 100%;
    margin: 0;
    background-color: #393939;
    padding: 10px;
}

When you use this these directives you end up hiding the Git selection to select a branch from the Brackets Git plugin:
![git selection not visible](https://cloud.githubusercontent.com/assets/2193139/7384480/42b31098-edf1-11e4-8368-c951c91a32d8.png)

If I simply comment out the width:100% part things work again:
![git selection visible](https://cloud.githubusercontent.com/assets/2193139/7384488/51075b7c-edf1-11e4-8ac4-a537841def80.png)

As both your plugin and the Git plugin are very popular it would be nice if the CSS for your themes did not obscure the select branch button.

**Comment by wormeyman** [comment]
Hey @mfromin i'll take a look into this since it seems like an easy CSS fix, i'll try to get it done today otherwise it'll have to wait until next week.

**Comment by mfromin** [comment]
For the record this seems to make things much better:

```
#project-files-header .btn-alt-quiet {
    /* Folder button */
    width: 40%;
    text-overflow: ellipsis;
    border-radius: 0;
    margin: 4px;
    background-color: #393939;
    padding: 5px;
}
```

The elipsis option stops super long folder names from overwhelming the button's size.

**Comment by wormeyman** [comment]
- Carbon Blue
- Idle Fingers
- Obsidian

Seem to have problems

**Comment by wormeyman** [comment]
https://github.com/Jacse/themes-for-brackets/archive/Sidebar-fixes.zip

Try installing that Zip and double check for me and if you think it works great i publish it.

**Comment by mfromin** [comment]
It does fix things.  

I prefer adding the width and text-overflow from my example as it stops the button from growing overly wide if you have a long folder name but otherwise its fine.

**Comment by wormeyman** [comment]
I try not to combine width and padding as it can break things https://github.com/CSSLint/csslint/wiki/Beware-of-box-model-size

The text-overflow is actually pretty nice but adobe doesn't have it on their themes so for now i'll leave it out, fell free to keep it your branch however.

**Comment by Jacse** [comment]
I agree, following Brackets is the best way to go about it.
