### ISSUE TITLE
Stone age theme collapse icon missplaces

### ISSUE THREAD

**Issue by glorindel** [Jacse/themes-for-brackets#128]
![brackets](https://cloud.githubusercontent.com/assets/4254129/8564433/36d11fc6-254c-11e5-8275-f1422137007c.PNG)

as you can see collapse icon move to the code

**Comment by wormeyman** [comment]
I missed this report when i was on vacation, so sorry!

**Comment by wormeyman** [comment]
@Jacse Please upload the new version.

**Comment by glorindel** [comment]
Thank you :D i fixed it myself next day after I posted it :)
but if i donwload it on other pc it would help me :) and others too

have a nice day! and thank you for your work!

On 20 July 2015 at 23:59, Eric J <notifications@github.com> wrote:

> @Jacse <https://github.com/Jacse> Please upload the new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jacse/themes-for-brackets/issues/128#issuecomment-123060318>
> .
>



-- 
Chceme lámať okovy, chceme rozbiť kamene nášho mesta,
áno, to sme my, chceme otvoriť brány Kráľa Krista.
Chceme vidieť národy, ako na každom rohu chvália Pána,
tak to sme my, generácia, ktorá práve vstáva.

eSPé -cd On - Bláznovstvo

**Comment by Jacse** [comment]
Currently on vacation as well @wormeyman, will get to a computer and upload asap

**Comment by Jacse** [comment]
Uploaded :+1:
